### ISSUE TITLE
数据

### ISSUE THREAD

**Issue by jiashizuo** [AngusMonroe/ContrastPool#2]
你好请问数据的bin文件是怎么获得的？比如“/path/to/data/abide_AAL116.bin”数据

**Comment by AngusMonroe** [comment]
All Preprocessed data used in this paper are published in [this paper](https://proceedings.neurips.cc/paper_files/paper/2023/file/44e3a3115ca26e5127851acd0cedd0d9-Paper-Datasets_and_Benchmarks.pdf). 
You can download the bin files from [this figshare](https://auckland.figshare.com/articles/dataset/NeurIPS_2022_Datasets/21397377).
Data splits and configurations are stored in `./data/` and `./configs/`. If you want to process your own data, please check the dataloader script `./data/BrainNet.py`.

**Comment by rookie688** [comment]
我还是没找到.BIN文件

**Comment by pcppp** [comment]
how can I get the adni.zip file? I did not find adni.zip in this link.[figshare](https://auckland.figshare.com/articles/dataset/NeurIPS_2022_Datasets/21397377?file=42754021)Thanks a lot!
